### ISSUE TITLE
Metti la scala, togli Minala

### ISSUE THREAD

**Issue by BurningHAM18** [cttynul/needflix#1]
Nuova feature: version check, dato che fai tanti commit belli e blu
Problema: quella ****** di messagebox ad ogni spunta della sezione anime è un ottimo modo per convincere le persone ad essere favorevoli alla pena di morte

bell' algoritmo per gli episodi :neckbeard: :neckbeard: :neckbeard:

**Comment by cttynul** [comment]
Tutto verrà risolto nella prima release pubblica <3.
